Repository thoth-station/s2i-generic-data-science-notebook, pull requests merged in 2021-06, with the labels that each got.

#20 enable plugin for python editor
  .aicoe-ci.yaml
  .s2i/bin/assemble
  Pipfile
  Pipfile.lock
Labels: approved, kind/feature, sig/user-experience, size/XL, size/XXL

#32 enable users to use pre-commit in the notebooks
  Pipfile
  Pipfile.lock
Labels: approved, size/M

#35 fix match of pipfile with requirements.in
  requirements.in
Labels: approved, size/XS

#36 Add numpy
  Pipfile
  README.md
  requirements.in
Labels: approved, size/S
