Repository thoth-station/s2i-generic-data-science-notebook, pull requests merged in 2021-04, with the labels that each got.

#14 update extension list
  README.md
Labels: approved, size/XS

#18 Minor updates
  .aicoe-ci.yaml
  .pre-commit-config.yaml
  .prow.yaml
  .s2i/bin/assemble
  .thoth.yaml
  Pipfile
  Pipfile.lock
Labels: size/M

#19 enable jupyterlab-s3-browser extension for browsing s3 storage
  .s2i/bin/assemble
  Pipfile
  Pipfile.lock
  README.md
Labels: approved, kind/feature, sig/docs, sig/user-experience, size/M
